/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tis_pos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2class-009
 */
public class PosMain extends javax.swing.JFrame {
	static int ck = 1;
	ShowListDAO Sld=new ShowListDAO();
    /**
     * Creates new form PosMain
     */
    public PosMain() {
        initComponents();
         setSize(new java.awt.Dimension(1280,760));
         this.tbReSal.addChangeListener(new ChangeListener() {
             public void stateChanged(ChangeEvent e) {
                ArrayList<Dsc_VO> arr= Sld.makeSoldInfo();
                System.out.println("샐삽입");
                showSoldInfo(arr);
             }});
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBG = new javax.swing.JPanel();
        tbReSal = new javax.swing.JTabbedPane();
        tbSal = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        laTitle = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        barImage = new javax.swing.JLabel();
        ftBarcode = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();
        byClear = new javax.swing.JButton();
        byDiscount = new javax.swing.JButton();
        lbSubTotal = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbReceived = new javax.swing.JLabel();
        lbChange = new javax.swing.JLabel();
        lbChangeNum = new javax.swing.JLabel();
        lbTotalNum = new javax.swing.JLabel();
        lbDiscountNum = new javax.swing.JLabel();
        lbSubTotalNum = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        btSubmit = new javax.swing.JButton();
        btAdmin = new javax.swing.JButton();
        tfReceived = new javax.swing.JTextField();
    

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jBG.setBackground(new java.awt.Color(81, 13, 117));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "상품번호", "상품명", "가격", "수량", "유통기한"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbSal.setViewportView(jTable1);

        tbReSal.addTab("결제", tbSal);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "결제시간", "No", "상품번호", "상품명", "가격", "수량"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        tbReSal.addTab("최근결제내역", jScrollPane4);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        laTitle.setFont(new java.awt.Font("맑은 고딕", 1, 30)); // NOI18N
        laTitle.setForeground(new java.awt.Color(255, 255, 255));
        laTitle.setText("주문내역");

        lbdate.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lbdate.setForeground(new java.awt.Color(180, 255, 229));
        lbdate.setText(Sld.showdate());
        
        bt1.setBackground(new java.awt.Color(180, 255, 229));
        bt1.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        bt1.setForeground(new java.awt.Color(81, 13, 117));
        bt1.setText("종량제봉투[10ea]");
        bt1.setActionCommand("L0011");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setBackground(new java.awt.Color(180, 255, 229));
        bt2.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        bt2.setForeground(new java.awt.Color(81, 13, 117));
        bt2.setText("아이시스[6ea]");
        bt2.setActionCommand("P0053");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(153, 204, 255));
        bt3.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        bt3.setForeground(new java.awt.Color(81, 13, 117));
        bt3.setText("봉투");
        bt3.setActionCommand("L0052");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(153, 204, 255));
        bt4.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        bt4.setForeground(new java.awt.Color(81, 13, 117));
        bt4.setText("택배");
        bt4.setActionCommand("L0051");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setBackground(new java.awt.Color(180, 255, 229));
        bt5.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        bt5.setForeground(new java.awt.Color(81, 13, 117));
        bt5.setText("교통카드충전");
        bt5.setActionCommand("L0055");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setBackground(new java.awt.Color(180, 255, 229));
        bt6.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        bt6.setForeground(new java.awt.Color(81, 13, 117));
        bt6.setText("상품권");
        bt6.setActionCommand("L0053");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        barImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/barcode.png"))); // NOI18N

        ftBarcode.setBackground(new java.awt.Color(255, 255, 255));
        ftBarcode.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        ftBarcode.setForeground(new java.awt.Color(81, 13, 117));
        ftBarcode.setToolTipText("");
     

        btRegister.setBackground(new java.awt.Color(180, 255, 229));
        btRegister.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        btRegister.setForeground(new java.awt.Color(81, 13, 117));
        btRegister.setText("등록");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        byClear.setBackground(new java.awt.Color(255, 153, 153));
        byClear.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        byClear.setForeground(new java.awt.Color(81, 13, 117));
        byClear.setText("취소");
        byClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byClearActionPerformed(evt);
            }
        });

        byDiscount.setBackground(new java.awt.Color(153, 204, 255));
        byDiscount.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        byDiscount.setForeground(new java.awt.Color(81, 13, 117));
        byDiscount.setText("행사");
        byDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byDiscountActionPerformed(evt);
            }
        });

        lbSubTotal.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lbSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        lbSubTotal.setText("소   계");

        lbDiscount.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lbDiscount.setForeground(new java.awt.Color(255, 255, 255));
        lbDiscount.setText("할   인");

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("합   계");

        lbReceived.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lbReceived.setForeground(new java.awt.Color(255, 255, 255));
        lbReceived.setText("받은돈");

        lbChange.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lbChange.setForeground(new java.awt.Color(255, 255, 255));
        lbChange.setText("거스름");

        lbChangeNum.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lbChangeNum.setForeground(new java.awt.Color(255, 153, 153));
        lbChangeNum.setText("거스름돈");//거스름돈
        tfReceived.setText("");//받은돈
        tfReceived.addActionListener(new ActionListener() {
        	
        	@Override
        	public void actionPerformed(ActionEvent e)
        	{
        		btSubmitActionPerformed(e);
        	}
        });
        
        ftBarcode.addActionListener(new ActionListener() {
        	
        	@Override
        	public void actionPerformed(ActionEvent e)
        	{
        		btRegisterActionPerformed(e);
        	}
        });
        
        
        
        lbTotalNum.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lbTotalNum.setForeground(new java.awt.Color(153, 204, 255));
        lbTotalNum.setText("");
      //합계= 소계총합-할인금액
        lbDiscountNum.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lbDiscountNum.setForeground(new java.awt.Color(255, 255, 255));
        lbDiscountNum.setText("");
      //숫자
        lbSubTotalNum.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lbSubTotalNum.setForeground(new java.awt.Color(180, 255, 229));
        lbSubTotalNum.setText("소계총합");
        
      //숫자
        btCancel.setBackground(new java.awt.Color(255, 153, 153));
        btCancel.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        btCancel.setForeground(new java.awt.Color(81, 13, 117));
        btCancel.setText("모두취소");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btSubmit.setBackground(new java.awt.Color(180, 255, 229));
        btSubmit.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        btSubmit.setForeground(new java.awt.Color(81, 13, 117));
        btSubmit.setText("결제");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        btAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btAdmin.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btAdmin.setForeground(new java.awt.Color(81, 13, 117));
        btAdmin.setText("관리자모드");
        btAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdminActionPerformed(evt);
            }
        });
        
     
    

        javax.swing.GroupLayout jBGLayout = new javax.swing.GroupLayout(jBG);
        jBG.setLayout(jBGLayout);
        jBGLayout.setHorizontalGroup(
            jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBGLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(116, 116, 116)
                        .addComponent(laTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbdate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAdmin, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbReSal, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jBGLayout.createSequentialGroup()
                                .addComponent(barImage)
                                .addGap(18, 18, 18)
                                .addComponent(ftBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(byClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(byDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jBGLayout.createSequentialGroup()
                                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jBGLayout.createSequentialGroup()
                                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createSequentialGroup()
                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createSequentialGroup()
                                    .addComponent(btSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createSequentialGroup()
                                    .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbReceived)
                                            .addComponent(lbChange))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbSubTotal)
                                            .addComponent(lbDiscount)
                                            .addComponent(jLabel8)))
                                    .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jBGLayout.createSequentialGroup()
                                            .addGap(94, 94, 94)
                                            .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbTotalNum)
                                                .addComponent(lbDiscountNum)
                                                .addComponent(lbSubTotalNum)))
                                        .addGroup(jBGLayout.createSequentialGroup()
                                            .addGap(91, 91, 91)
                                            .addComponent(lbChangeNum))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBGLayout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(tfReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18))))))
                .addGap(30, 30, 30))
        );
        jBGLayout.setVerticalGroup(
            jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBGLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laTitle)
                    .addComponent(jLabel1)
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addComponent(lbdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAdmin)))
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tbReSal, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jBGLayout.createSequentialGroup()
                                .addComponent(lbSubTotal)
                                .addGap(20, 20, 20)
                                .addComponent(lbDiscount)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lbReceived)
                                .addGap(20, 20, 20)
                                .addComponent(lbChange, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jBGLayout.createSequentialGroup()
                                .addComponent(lbSubTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbDiscountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lbTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbChangeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jBGLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ftBarcode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(byClear)
                                .addComponent(byDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRegister))
                            .addComponent(barImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        
    	if(Sld.cking_product_num(evt.getActionCommand()))//재고쳌
    	{
    	ArrayList<ShowListVO> arr2 =Sld.insertViewList(evt.getActionCommand()); 
    	  showTable(arr2);
    	  lbSubTotalNum.setText(Sld.cal_all_sum());
    	  lbTotalNum.setText(Sld.total(lbDiscountNum.getText(),lbSubTotalNum.getText()));  
        }
    	else
    		JOptionPane.showMessageDialog(this, "입력한 상품의 재고가 부족합니다");
    	  //봉투
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
    	   	if(Sld.cking_product_num(evt.getActionCommand()))//재고쳌
        	{
    	   	  	ArrayList<ShowListVO> arr2 =Sld.insertViewList(evt.getActionCommand()); 
    	    	  showTable(arr2);
    	    	  lbSubTotalNum.setText(Sld.cal_all_sum());
    	    	  lbTotalNum.setText(Sld.total(lbDiscountNum.getText(),lbSubTotalNum.getText()));  
    	    	  
        	}
        	else
        		JOptionPane.showMessageDialog(this, "입력한 상품의 재고가 부족합니다");
    	  //아이시스
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
    	if(Sld.cking_product_num(evt.getActionCommand()))//재고쳌
    	{
    	   	ArrayList<ShowListVO> arr2 =Sld.insertViewList(evt.getActionCommand()); 
    	  	 showTable(arr2);
    	  	lbSubTotalNum.setText(Sld.cal_all_sum());
    	    lbTotalNum.setText(Sld.total(lbDiscountNum.getText(),lbSubTotalNum.getText()));
    	}
    	else
    		JOptionPane.showMessageDialog(this, "입력한 상품의 재고가 부족합니다");
    	
  
  	  //쓰봉
    }//GEN-LAST:event_bt1ActionPerformed

  
   
    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
    	  
    	  System.out.println("등록");
    	  String tmbarc=ftBarcode.getText();
    	 	if(tmbarc.trim().isEmpty()||tmbarc==null)
        	{
        		JOptionPane.showMessageDialog(this, "바코드값을 입력하세요");
        		ftBarcode.requestFocus();
        		return;
        		
        	}

		if (Sld.ck_List(tmbarc)) {
			if (Sld.checkDate(tmbarc)) {
				JOptionPane.showMessageDialog(this, "유통기한이 지난 상품입니다.");
				System.out.println("유통기한이 지난 상품입니다.");
				ftBarcode.requestFocus();
			} else {
				if (Sld.cking_product_num(tmbarc))// 재고쳌
				{
					ArrayList<ShowListVO> arr2 = Sld.insertViewList(ftBarcode.getText());
					showTable(arr2);
					lbSubTotalNum.setText(Sld.cal_all_sum());
					lbTotalNum.setText(Sld.total(lbDiscountNum.getText(), lbSubTotalNum.getText()));
				} else
					JOptionPane.showMessageDialog(this, "입력한 상품의 재고가 부족합니다");

			}

		} else {
			JOptionPane.showMessageDialog(this, "상품이 없거나 바코드 잘못 입력했습니다");
			ftBarcode.requestFocus();
		}
    	  

    }//GEN-LAST:event_btRegisterActionPerformed
  
    String [] colHeader= {"상품번호","상품명","가격","수량","유통기한"};
 
    
    public void showTable(ArrayList<ShowListVO> arr)
    {
    	//table.get
    	Object [][]data=new Object[arr.size()][5];
    	for(int i =0 ;i<arr.size();i++)
    	{
    		ShowListVO pp=arr.get(i);
    		for(int j=0;j<5;j++)
    		{
    			data[i][j]=getout(pp,j);
    		}
    	}
   
    	   DefaultTableModel model=new DefaultTableModel(data,colHeader) {
    	        boolean[] canEdit = new boolean [] {false, false, false, true, false};
    	        @Override
    	         public boolean isCellEditable(int rowIndex, int columnIndex) {
    	             return canEdit [columnIndex];
    	             }   
    	        
    	        @Override
    	          public void setValueAt(Object val,int row, int col) {
    	             if(col==3) {
    	                String str=val.toString();
    	                System.out.println("val: "+val+", data1: "+data[row][col]);
    	                data[row][col]=new Integer(str);
    	                System.out.println("str: "+str+", data2: "+data[row][col]);
    	                int n=Sld.updateQuty(data[row][0].toString(), 
    	                      new Integer(data[row][col].toString()).intValue());
    	             }
    	             super.setValueAt(val, row, col);
    	          }
    	     };
    	     jTable1.setModel(model);
    }
   
    public void ClearTable()
    {
    	//table.get
    	Object [][]data=new Object[1][5];
    	for(int i =0 ;i<1;i++)
    	{
    		for(int j=0;j<5;j++)
    		{
    			data[i][j]="";
    		}
    	}
   
    	DefaultTableModel model=new DefaultTableModel(data,colHeader);
    	jTable1.setModel(model);
    }
    /*
     * 		String pronum=rs.getString(1);
			String name =rs.getString(2);
			int price=rs.getInt(3);
			int count=rs.getInt(4);
			java.sql.Date wdate=rs.getDate(5);
			int customnum=rs.getInt(6);
     */
    public Object getout(ShowListVO pp,int i)
    {
    	switch (i)
		{
		case 0: 
			return pp.getProduct_num();
		case 1:
			return pp.getProduct_name();
		case 2:
			return pp.getPrice();
		case 3:
			return pp.getCount();
		case 4:
			return pp.getDate_out();
		default:
			return -1;
		}
    }

    private void byClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byClearActionPerformed
    	System.out.println("취소");
    	if(jTable1.getSelectedRow() != -1) {
  	 		Object obj=jTable1.getValueAt(jTable1.getSelectedRow(),0);
  	 		System.out.println(obj.toString());
  	 		String 상품코드=obj.toString();
  	 		
  	 		
  	 		showTable(Sld.deleteViewList(상품코드));
  	 		//String tmppp=(Sld.cal_all_sum().isEmpty()) ? "0" :Sld.cal_all_sum();
  	 		lbSubTotalNum.setText(Sld.cal_all_sum());
      	    lbTotalNum.setText(Sld.total(lbDiscountNum.getText(),lbSubTotalNum.getText()));  
  	 		
  	 	}
    	
    }

    private void byDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byDiscountActionPerformed
    	System.out.println("행사");
    	if(ck_num(lbSubTotalNum.getText()))
    	{
    		String tmp =Sld.discount(lbSubTotalNum.getText());
    		lbDiscountNum.setText(tmp);
        	lbTotalNum.setText(Sld.total(lbDiscountNum.getText(),lbSubTotalNum.getText()));  
    	}
    	else
    	{
    		JOptionPane.showMessageDialog(this, "상품이 없습니다");
    	}
    
    }//GEN-LAST:event_byDiscountActionPerformed

public boolean ck_num(String tt)
{
	 try {
	      Double.parseDouble(tt);
	      return true;
	  } catch(NumberFormatException e) {
	      return false;
	  }
}
    
private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btCancelActionPerformed
    if (ck == 0) {
       ClearTable();
       Sld.all_cancel();
       ck = 1;
       lbChangeNum.setText("");
       lbTotalNum.setText("");
       tfReceived.setText("");
       lbDiscountNum.setText("");
       lbSubTotalNum.setText("");
    } else {
       JOptionPane.showMessageDialog(this, "상품이 없습니다.");
       //올취소
    }
}
    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
       System.out.println("결제버튼 낙결");
       if(change())
       {
    	   
    	   Sld.insertAll(); 
           ClearTable();
           ck=1;
       }
     
    }//GEN-LAST:event_btSubmitActionPerformed


    public boolean change() {
        try {
           int totalInt = 0;
           int receivedInt = 0;

           // tfReceived.setText("이거뭐냐");//받은돈
           String total = lbTotalNum.getText();
           String received = tfReceived.getText();

           if (received.trim().isEmpty() || received == null) {
              totalInt = Integer.parseInt(total);
             System.out.println(total);

              receivedInt = 0;
           } else if (!(received.trim().isEmpty()) && received != null) {
              totalInt = Integer.parseInt(total);
              receivedInt = Integer.parseInt(received);
              receivedInt = receivedInt - totalInt;
              if (receivedInt < 0) {
                 JOptionPane.showMessageDialog(this, "금액이 부족합니다");
                 tfReceived.requestFocus();
                 return false;
              }
           }

           lbChangeNum.setText(Integer.toString(receivedInt));// 거스름돈
           lbTotalNum.setText("");
           tfReceived.setText("");
           lbDiscountNum.setText("");
           lbSubTotalNum.setText("");

           return true;
           
        } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "상품과 금액을 입력해주세요");
           return false;
        }
     }
    private void btAdminActionPerformed(java.awt.event.ActionEvent evt) {
    	Object obj=evt.getSource();
    	PasswordforAdmin pa=new PasswordforAdmin();
    	if(obj==btAdmin) {
    		pa.pack();
    		pa.setLocation(500,300);
			pa.setVisible(true);
    	}
    }

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
    	ArrayList<ShowListVO> arr2 =Sld.insertViewList(evt.getActionCommand()); 
    	  showTable(arr2);
    	  lbSubTotalNum.setText(Sld.cal_all_sum());
    	  lbTotalNum.setText(Sld.total(lbDiscountNum.getText(),lbSubTotalNum.getText()));  
    	  
    	  //택배
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
    	ArrayList<ShowListVO> arr2 =Sld.insertViewList(evt.getActionCommand()); 
    	  showTable(arr2);
    	  lbSubTotalNum.setText(Sld.cal_all_sum());
    	  lbTotalNum.setText(Sld.total(lbDiscountNum.getText(),lbSubTotalNum.getText()));  
    	  
    	  //교통카드
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
    	
     	if(Sld.cking_product_num(evt.getActionCommand()))//재고쳌
        {
     		ArrayList<ShowListVO> arr2 =Sld.insertViewList(evt.getActionCommand()); 
      	  showTable(arr2);
      	  lbSubTotalNum.setText(Sld.cal_all_sum());
      	  lbTotalNum.setText(Sld.total(lbDiscountNum.getText(),lbSubTotalNum.getText()));  
 
        }
    	else
    		JOptionPane.showMessageDialog(this, "입력한 상품의 재고가 부족합니다");
    	
    	  //상품권
    }//GEN-LAST:event_bt6ActionPerformed


    String[] colHeader2 = { "결제시간", "No", "상품번호", "상품명", "가격", "수량" };
    private void showSoldInfo(ArrayList<Dsc_VO> arr) {
      // 거래내역 테이블 보기
      Object[][] data = new Object[arr.size()][6];
      for (int i = 0; i < data.length; i++) {
         Dsc_VO dv = arr.get(i);
         data[i][0] = dv.getSalesdate();
         data[i][1] = dv.getcustomer_no();
         data[i][2] = dv.getproduct_no();
         data[i][3] = dv.getproduct_name();
         data[i][4] = dv.getoutput_price();
         data[i][5] = dv.getsales_vol();
         DefaultTableModel model=new DefaultTableModel(data,colHeader2) {
             boolean[] canEdit = new boolean [] {false, false, false, false, false};
             @Override
              public boolean isCellEditable(int rowIndex, int columnIndex) {
                  return canEdit [columnIndex];
                  }   
          };
          jTable3.setModel(model);
      }
   }// -------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PosMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PosMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PosMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PosMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PosMain().setVisible(true);
            }
        });
        
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barImage;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton btAdmin;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton btSubmit;
    private javax.swing.JButton byClear;
    private javax.swing.JButton byDiscount;
    private javax.swing.JTextField ftBarcode;
    private javax.swing.JPanel jBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel laTitle;
    private javax.swing.JLabel lbChange;
    private javax.swing.JLabel lbChangeNum;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbDiscountNum;
    private javax.swing.JLabel lbReceived;
    private javax.swing.JLabel lbSubTotal;
    private javax.swing.JLabel lbSubTotalNum;
    private javax.swing.JLabel lbTotalNum;
    private javax.swing.JLabel lbdate;
    private javax.swing.JTabbedPane tbReSal;
    private javax.swing.JScrollPane tbSal;
    private javax.swing.JTextField tfReceived;
    // End of variables declaration//GEN-END:variables
}
